print("== Complex ==")
try Profiling().complex()
print("== Dictionary ==")
try Profiling().dictionary()
print("== Data ==")
try Profiling().data()
print("== String ==")
try Profiling().string()
print("== Int ==")
try Profiling().int()
